replicaCount: 2

image:
  repository: ibmwebmethods.azurecr.io/apigateway-minimal
  pullPolicy: IfNotPresent
  tag: "11.1"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  #readOnlyRootFilesystem: true
  #runAsUser: 1000

ingresses:
  ui:
    defaultHost: "apigateway-ui.local"
    enabled: true
    className: "nginx"
    tls:
      - secretName: "tls-cert"
  rt:
    defaultHost: "apigateway-rt.local"
    enabled: true
    className: "nginx"
    tls:
      - secretName: "tls-cert"
  admin:
    defaultHost: "apigateway-admin.local"
    enabled: true
    className: "nginx"
    tls:
      - secretName: "tls-cert"

resources:
  apigwContainer:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      cpu: 8
      memory: 8Gi


autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceMonitor:
  enabled: true


metering:
  enabled: false

elasticsearch:
  deploy: true
  version: 8.17.3
  storageClassName: "local-path"

  defaultNodeSet:
    count: 3

kibana:
  version: 8.17.3
  count: 1
