replicaCount: 1

image:
  repository: ibmwebmethods.azurecr.io/devportal
  pullPolicy: IfNotPresent
  tag: "11.1"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


ingress:
  enabled: false
  defaultHostname: devportal.mydomain.com
  className: ""
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  devportalContainer:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

devportal:
  # -- HTTP listening port. Use on wM version 10.15 (default): `8083`, 11.0: `8080` 
  port: 8080

elasticsearch:
  deploy: true
  version: 8.12.2
