replicaCount: 1

image:
  repository: ibmwebmethods.azurecr.io/devportal
  pullPolicy: IfNotPresent
  tag: "11.1"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  #runAsNonRoot: true
  #runAsUser: 1000


ingress:
  enabled: true
  defaultHostname: devportal.local
  className: "nginx"
  tls:
    - secretName: "tls-cert"

resources: 
  devportalContainer:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

devportal:
  # -- HTTP listening port. `8080` for version >= 11.x, otherwise `8083`
  port: 8080

elasticsearch:
  deploy: true
  version: 8.12.2
  defaultNodeSet:
    count: 1