replicaCount: 1


image:
  repository: "ibmwebmethods.azurecr.io/webmethods-microservicesruntime"
  pullPolicy: IfNotPresent
  tag:        "11.1"


microservicesruntime:

  licenseKeyProvided: false

  memoryHeap:
    min: "512M"
    max: "1024M"

  propertiesFile: 
    content: |
      user.Administrator.password=$secret{MSR_ADMIN_PASSWORD}

secretMounts:
  - name: msr-secrets
    secretName: msr-secrets
    path: /etc/secrets

secretVolumes:
  - name: msr-secrets
    secretName: msr-obs


serviceAccount:
  create: true
  name: "msr-obs"


podSecurityContext:
  runAsNonRoot: true
  #fsGroup: 1724

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  #readOnlyRootFilesystem: true
  #runAsUser: 1000

ingress:
  enabled: true
  defaultHostname: msr.sttlab.local
  className: "nginx"
  hosts:
    - host: "msr.sttlab.local"
      paths:
        - path: /
          pathType: Prefix
          port: 5555
  tls: 
    - secretName: tls-cert

resources:
  msrContainer:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

metering:
  enabled: false
